name: CI

on:
  push:
    branches: [ master, main, '**/p1-p2*' ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    name: Test & Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Run Go Unit Tests
        run: go test -v ./...

      - name: Build Spin-HUD Binary
        run: go build -v .
